#!/bin/ash
mount -o remount,rw /dev/xvda1 /
mount -t proc proc /proc
mount -t sysfs sysfs /sys
if [ -d /sys/block/zram0 ] ; then
	grep MemTotal: /proc/meminfo | awk '{print $2*1024}' > /sys/block/zram0/disksize
	mkswap /dev/zram0 && swapon /dev/zram0
fi
hostname bbdomu
ifconfig lo 127.0.0.1
ifconfig eth0 up
udhcpc 
